version: '3'

services:
  instances-api:
    image: 1337kavin/piped-instances-api
    # build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      INFLUXDB_URL: TODO
      INFLUXDB_TOKEN: TODO
      INFLUXDB_DATABASE: TODO
    restart: unless-stopped
